# Functional test definitions
# Lists all functional tests with proper grouping and cost assignments

find_package(Python3 COMPONENTS Interpreter REQUIRED)

# Detect multi-config generators (MSVC, Xcode) vs single-config (Ninja, Makefiles)
# Multi-config generators place binaries in bin/<CONFIG>/, single-config in bin/
get_property(is_multi_config GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)

if(NOT DEFINED ENABLE_WALLET)
    set(ENABLE_WALLET ON)
endif()

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(IS_LINUX TRUE)
else()
    set(IS_LINUX FALSE)
endif()

if(NOT CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(IS_POSIX TRUE)
else()
    set(IS_POSIX FALSE)
endif()

option(ENABLE_EXTENDED_FUNCTIONAL_TESTS "Enable extended/slow functional tests" OFF)
option(ENABLE_PREVIOUS_RELEASES_TESTS "Enable tests requiring previous Bitcoin releases" OFF)
option(ENABLE_USDT_TESTS "Enable USDT tracepoint tests (requires Linux + BPF permissions)" OFF)
option(ENABLE_SPECIAL_NETWORK_TESTS "Enable tests requiring special network configuration" OFF)
option(ENABLE_RPC_COVERAGE "Enable RPC coverage tracking for functional tests" OFF)

# Counter for unique portseed values to prevent port collisions in parallel test runs
set(FUNCTIONAL_TEST_PORTSEED_COUNTER 0 CACHE INTERNAL "")

# Helper to add functional tests
function(add_functional_test test_name test_script)
    set(options "")
    set(oneValueArgs COST WORKING_DIRECTORY)
    set(multiValueArgs LABELS DEPENDS)
    cmake_parse_arguments(AFT "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT AFT_WORKING_DIRECTORY)
        set(AFT_WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    endif()

    if(NOT AFT_COST)
        set(AFT_COST 1)
    endif()

    # Parse script name and arguments
    string(REPLACE " " ";" test_parts "${test_script}")
    list(GET test_parts 0 script_name)
    list(LENGTH test_parts num_parts)

    # Get current portseed and increment for next test
    set(portseed ${FUNCTIONAL_TEST_PORTSEED_COUNTER})
    math(EXPR next_portseed "${FUNCTIONAL_TEST_PORTSEED_COUNTER} + 1")
    set(FUNCTIONAL_TEST_PORTSEED_COUNTER ${next_portseed} CACHE INTERNAL "" FORCE)

    set(base_args --cachedir=${CMAKE_BINARY_DIR}/test/cache --portseed=${portseed})
    if(DEFINED FUNCTIONAL_TESTS_TIMEOUT_FACTOR)
        list(APPEND base_args --timeout-factor=${FUNCTIONAL_TESTS_TIMEOUT_FACTOR})
    endif()

    if(ENABLE_RPC_COVERAGE)
        file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/coverage")
        list(APPEND base_args --coveragedir=${CMAKE_CURRENT_BINARY_DIR}/coverage)
    endif()

    if(num_parts GREATER 1)
      # We've got arguments
        list(SUBLIST test_parts 1 -1 script_args)
        add_test(
            NAME "bitcoin.functional.${test_name}"
            COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/functional/${script_name} ${base_args} ${script_args}
            WORKING_DIRECTORY ${AFT_WORKING_DIRECTORY}
        )
    else()
        add_test(
            NAME "bitcoin.functional.${test_name}"
            COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/functional/${script_name} ${base_args}
            WORKING_DIRECTORY ${AFT_WORKING_DIRECTORY}
        )
    endif()

    set_tests_properties("bitcoin.functional.${test_name}" PROPERTIES
        LABELS "functional"
        COST ${AFT_COST}
        FIXTURES_REQUIRED "functional_cache"
        ENVIRONMENT "CMAKE_CONFIG=$<$<BOOL:${is_multi_config}>:$<CONFIG>>;TSAN_OPTIONS=suppressions=${CMAKE_SOURCE_DIR}/test/sanitizer_suppressions/tsan:halt_on_error=1:second_deadlock_stack=1;LSAN_OPTIONS=suppressions=${CMAKE_SOURCE_DIR}/test/sanitizer_suppressions/lsan;UBSAN_OPTIONS=suppressions=${CMAKE_SOURCE_DIR}/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1:report_error_type=1;ASAN_OPTIONS=detect_leaks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1"
    )

    if(AFT_LABELS)
        set_tests_properties("bitcoin.functional.${test_name}" PROPERTIES
            LABELS "functional;${AFT_LABELS}"
        )
    endif()
endfunction()

# Extended/slow tests (>5 minutes) - COST 300+
if(ENABLE_EXTENDED_FUNCTIONAL_TESTS)
    add_functional_test(feature_pruning "feature_pruning.py" COST 500)
    add_functional_test(feature_dbcrash "feature_dbcrash.py" COST 400)
    add_functional_test(feature_index_prune "feature_index_prune.py" COST 350)
endif()

# Long-running base tests (~2-5 minutes) - COST 200-299
add_functional_test(feature_fee_estimation "feature_fee_estimation.py" COST 280)
add_functional_test(feature_block "feature_block.py" COST 260)
add_functional_test(mempool_ephemeral_dust "mempool_ephemeral_dust.py" COST 250)
add_functional_test(p2p_opportunistic_1p1c "p2p_opportunistic_1p1c.py" COST 240)
add_functional_test(p2p_node_network_limited_v1 "p2p_node_network_limited.py --v1transport" COST 230)
add_functional_test(p2p_node_network_limited_v2 "p2p_node_network_limited.py --v2transport" COST 230)

# Medium tests (~1-2 minutes) - COST 100-199
add_functional_test(mining_getblocktemplate_longpoll "mining_getblocktemplate_longpoll.py" COST 180)
add_functional_test(p2p_segwit "p2p_segwit.py" COST 170)
add_functional_test(feature_maxuploadtarget "feature_maxuploadtarget.py" COST 160)
add_functional_test(feature_assumeutxo "feature_assumeutxo.py" COST 150)
add_functional_test(mempool_updatefromblock "mempool_updatefromblock.py" COST 140)
add_functional_test(mempool_persist "mempool_persist.py" COST 130)
add_functional_test(p2p_tx_download "p2p_tx_download.py" COST 120)
add_functional_test(feature_abortnode "feature_abortnode.py" COST 115)
add_functional_test(p2p_orphan_handling "p2p_orphan_handling.py" COST 110)
add_functional_test(feature_maxtipage "feature_maxtipage.py" COST 105)
add_functional_test(p2p_dns_seeds "p2p_dns_seeds.py" COST 100)

# Wallet tests (conditional on wallet support)
if(ENABLE_WALLET)
    add_functional_test(feature_taproot "feature_taproot.py" COST 270 LABELS "wallet")
    add_functional_test(wallet_conflicts "wallet_conflicts.py" COST 200 LABELS "wallet")
    add_functional_test(rpc_psbt "rpc_psbt.py" COST 120 LABELS "wallet")
    add_functional_test(wallet_fundrawtransaction "wallet_fundrawtransaction.py" COST 115 LABELS "wallet")
    add_functional_test(wallet_bumpfee "wallet_bumpfee.py" COST 110 LABELS "wallet")
    add_functional_test(wallet_v3_txs "wallet_v3_txs.py" COST 105 LABELS "wallet")
    add_functional_test(wallet_backup "wallet_backup.py" COST 100 LABELS "wallet")
    add_functional_test(feature_segwit_v2 "feature_segwit.py --v2transport" COST 95 LABELS "wallet")
    add_functional_test(feature_segwit_v1 "feature_segwit.py --v1transport" COST 95 LABELS "wallet")
    add_functional_test(wallet_avoidreuse "wallet_avoidreuse.py" COST 90 LABELS "wallet")
    add_functional_test(wallet_address_types "wallet_address_types.py" COST 85 LABELS "wallet")
    add_functional_test(wallet_basic "wallet_basic.py" COST 80 LABELS "wallet")
    add_functional_test(wallet_multiwallet "wallet_multiwallet.py" COST 75 LABELS "wallet")
    add_functional_test(wallet_multiwallet_usecli "wallet_multiwallet.py --usecli" COST 75 LABELS "wallet")
    add_functional_test(wallet_groups "wallet_groups.py" COST 70 LABELS "wallet")
    add_functional_test(wallet_taproot "wallet_taproot.py" COST 65 LABELS "wallet")
    add_functional_test(wallet_listtransactions "wallet_listtransactions.py" COST 60 LABELS "wallet")
    add_functional_test(wallet_miniscript "wallet_miniscript.py" COST 55 LABELS "wallet")
    add_functional_test(wallet_signer "wallet_signer.py" COST 50 LABELS "wallet")
    add_functional_test(wallet_listreceivedby "wallet_listreceivedby.py" COST 48 LABELS "wallet")
    add_functional_test(wallet_abandonconflict "wallet_abandonconflict.py" COST 46 LABELS "wallet")
    add_functional_test(wallet_anchor "wallet_anchor.py" COST 44 LABELS "wallet")
    add_functional_test(wallet_labels "wallet_labels.py" COST 42 LABELS "wallet")
    add_functional_test(wallet_hd "wallet_hd.py" COST 40 LABELS "wallet")
    add_functional_test(wallet_blank "wallet_blank.py" COST 38 LABELS "wallet")
    add_functional_test(wallet_keypool_topup "wallet_keypool_topup.py" COST 36 LABELS "wallet")
    add_functional_test(wallet_fast_rescan "wallet_fast_rescan.py" COST 34 LABELS "wallet")
    add_functional_test(wallet_gethdkeys "wallet_gethdkeys.py" COST 32 LABELS "wallet")
    add_functional_test(wallet_createwalletdescriptor "wallet_createwalletdescriptor.py" COST 30 LABELS "wallet")
    add_functional_test(wallet_txn_doublespend_mineblock "wallet_txn_doublespend.py --mineblock" COST 28 LABELS "wallet")
    add_functional_test(wallet_txn_doublespend "wallet_txn_doublespend.py" COST 28 LABELS "wallet")
    add_functional_test(tool_wallet "tool_wallet.py" COST 26 LABELS "wallet")
    add_functional_test(wallet_txn_clone "wallet_txn_clone.py" COST 24 LABELS "wallet")
    add_functional_test(wallet_txn_clone_segwit "wallet_txn_clone.py --segwit" COST 24 LABELS "wallet")
    add_functional_test(wallet_txn_clone_mineblock "wallet_txn_clone.py --mineblock" COST 24 LABELS "wallet")
    add_functional_test(wallet_avoid_mixing_output_types "wallet_avoid_mixing_output_types.py" COST 22 LABELS "wallet")
    add_functional_test(wallet_createwallet_usecli "wallet_createwallet.py --usecli" COST 20 LABELS "wallet")
    add_functional_test(wallet_createwallet "wallet_createwallet.py" COST 20 LABELS "wallet")
    add_functional_test(wallet_reindex "wallet_reindex.py" COST 18 LABELS "wallet")
    add_functional_test(wallet_reorgsrestore "wallet_reorgsrestore.py" COST 16 LABELS "wallet")
    add_functional_test(wallet_signrawtransactionwithwallet "wallet_signrawtransactionwithwallet.py" COST 14 LABELS "wallet")
    add_functional_test(wallet_transactiontime_rescan "wallet_transactiontime_rescan.py" COST 12 LABELS "wallet")
    add_functional_test(wallet_disable "wallet_disable.py" COST 10 LABELS "wallet")
    add_functional_test(wallet_change_address "wallet_change_address.py" COST 9 LABELS "wallet")
    add_functional_test(wallet_keypool "wallet_keypool.py" COST 8 LABELS "wallet")
    add_functional_test(wallet_descriptor "wallet_descriptor.py" COST 7 LABELS "wallet")
    add_functional_test(wallet_multisig_descriptor_psbt "wallet_multisig_descriptor_psbt.py" COST 6 LABELS "wallet")
    add_functional_test(wallet_miniscript_decaying_multisig_descriptor_psbt "wallet_miniscript_decaying_multisig_descriptor_psbt.py" COST 6 LABELS "wallet")
    add_functional_test(tool_signet_miner "tool_signet_miner.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_assumeutxo "wallet_assumeutxo.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_balance "wallet_balance.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_coinbase_category "wallet_coinbase_category.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_create_tx "wallet_create_tx.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_crosschain "wallet_crosschain.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_encryption "wallet_encryption.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_fallbackfee "wallet_fallbackfee.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_importdescriptors "wallet_importdescriptors.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_importprunedfunds "wallet_importprunedfunds.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_listdescriptors "wallet_listdescriptors.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_listsinceblock "wallet_listsinceblock.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_musig "wallet_musig.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_orphanedreward "wallet_orphanedreward.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_rescan_unconfirmed "wallet_rescan_unconfirmed.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_resendwallettransactions "wallet_resendwallettransactions.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_send "wallet_send.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_sendall "wallet_sendall.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_sendmany "wallet_sendmany.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_signmessagewithaddress "wallet_signmessagewithaddress.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_simulaterawtx "wallet_simulaterawtx.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_spend_unconfirmed "wallet_spend_unconfirmed.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_startup "wallet_startup.py" COST 5 LABELS "wallet")
    add_functional_test(wallet_timelock "wallet_timelock.py" COST 5 LABELS "wallet")
endif()

# Fast base tests (~30s-1min) - COST 50-99
add_functional_test(p2p_blockfilters "p2p_blockfilters.py" COST 65)
add_functional_test(feature_assumevalid "feature_assumevalid.py" COST 60)
add_functional_test(feature_bip68_sequence "feature_bip68_sequence.py" COST 55)
add_functional_test(rpc_packages "rpc_packages.py" COST 50)
add_functional_test(p2p_headers_sync_with_minchainwork "p2p_headers_sync_with_minchainwork.py" COST 48)
add_functional_test(p2p_feefilter "p2p_feefilter.py" COST 46)
add_functional_test(feature_csv_activation "feature_csv_activation.py" COST 44)
add_functional_test(p2p_sendheaders "p2p_sendheaders.py" COST 42)
add_functional_test(feature_config_args "feature_config_args.py" COST 40)
add_functional_test(mempool_limit "mempool_limit.py" COST 38)
add_functional_test(rpc_txoutproof "rpc_txoutproof.py" COST 36)
add_functional_test(rpc_orphans "rpc_orphans.py" COST 34)
add_functional_test(feature_reindex "feature_reindex.py" COST 32)
add_functional_test(feature_reindex_readonly "feature_reindex_readonly.py" COST 30)
add_functional_test(p2p_compactblocks "p2p_compactblocks.py" COST 28)
add_functional_test(p2p_compactblocks_blocksonly "p2p_compactblocks_blocksonly.py" COST 26)

# Very fast tests (<30s) - COST 1-49
add_functional_test(p2p_invalid_messages "p2p_invalid_messages.py" COST 25)
add_functional_test(rpc_createmultisig "rpc_createmultisig.py" COST 24)
add_functional_test(p2p_timeouts_v1 "p2p_timeouts.py --v1transport" COST 23)
add_functional_test(p2p_timeouts_v2 "p2p_timeouts.py --v2transport" COST 23)
add_functional_test(rpc_signer "rpc_signer.py" COST 22)
if(WITH_ZMQ)
    add_functional_test(interface_zmq "interface_zmq.py" COST 21)
endif()
add_functional_test(rpc_invalid_address_message "rpc_invalid_address_message.py" COST 20)
add_functional_test(rpc_validateaddress "rpc_validateaddress.py" COST 19)
add_functional_test(interface_bitcoin_cli "interface_bitcoin_cli.py" COST 18)
add_functional_test(mempool_resurrect "mempool_resurrect.py" COST 16)
if(BUILD_UTIL_CHAINSTATE)
    add_functional_test(tool_bitcoin_chainstate "tool_bitcoin_chainstate.py" COST 15)
endif()
add_functional_test(tool_utils "tool_utils.py" COST 14)
add_functional_test(rpc_getchaintips "rpc_getchaintips.py" COST 13)
add_functional_test(rpc_misc "rpc_misc.py" COST 12)
add_functional_test(p2p_1p1c_network "p2p_1p1c_network.py" COST 11)
add_functional_test(interface_rest "interface_rest.py" COST 10)
add_functional_test(mempool_spend_coinbase "mempool_spend_coinbase.py" COST 9)
add_functional_test(mempool_reorg "mempool_reorg.py" COST 8)
add_functional_test(p2p_block_sync_v1 "p2p_block_sync.py --v1transport" COST 7)
add_functional_test(p2p_block_sync_v2 "p2p_block_sync.py --v2transport" COST 7)
add_functional_test(interface_http "interface_http.py" COST 6)
add_functional_test(feature_addrman "feature_addrman.py" COST 5)
add_functional_test(feature_asmap "feature_asmap.py" COST 5)
add_functional_test(feature_blocksxor "feature_blocksxor.py" COST 5)
add_functional_test(feature_chain_tiebreaks "feature_chain_tiebreaks.py" COST 5)
add_functional_test(feature_cltv "feature_cltv.py" COST 5)
add_functional_test(feature_dersig "feature_dersig.py" COST 5)
add_functional_test(feature_discover "feature_discover.py" COST 5)
add_functional_test(feature_fastprune "feature_fastprune.py" COST 5)
add_functional_test(feature_filelock "feature_filelock.py" COST 5)
add_functional_test(feature_framework_miniwallet "feature_framework_miniwallet.py" COST 5)
add_functional_test(feature_framework_unit_tests "feature_framework_unit_tests.py" COST 5)
add_functional_test(feature_includeconf "feature_includeconf.py" COST 5)
add_functional_test(feature_init "feature_init.py" COST 5)
add_functional_test(feature_loadblock "feature_loadblock.py" COST 5)
add_functional_test(feature_logging "feature_logging.py" COST 5)
add_functional_test(feature_minchainwork "feature_minchainwork.py" COST 5)
add_functional_test(feature_notifications "feature_notifications.py" COST 5)
add_functional_test(feature_nulldummy "feature_nulldummy.py" COST 5)
add_functional_test(feature_port "feature_port.py" COST 5)
add_functional_test(feature_proxy "feature_proxy.py" COST 5)
add_functional_test(feature_rbf "feature_rbf.py" COST 5)
add_functional_test(feature_reindex_init "feature_reindex_init.py" COST 5)
add_functional_test(feature_signet "feature_signet.py" COST 5)
add_functional_test(feature_startupnotify "feature_startupnotify.py" COST 5)
add_functional_test(feature_uacomment "feature_uacomment.py" COST 5)
add_functional_test(feature_utxo_set_hash "feature_utxo_set_hash.py" COST 5)
add_functional_test(feature_versionbits_warning "feature_versionbits_warning.py" COST 5)
add_functional_test(interface_rpc "interface_rpc.py" COST 5)
add_functional_test(mempool_accept "mempool_accept.py" COST 5)
add_functional_test(mempool_accept_wtxid "mempool_accept_wtxid.py" COST 5)
add_functional_test(mempool_cluster "mempool_cluster.py" COST 5)
add_functional_test(mempool_dust "mempool_dust.py" COST 5)
add_functional_test(mempool_expiry "mempool_expiry.py" COST 5)
add_functional_test(mempool_package_limits "mempool_package_limits.py" COST 5)
add_functional_test(mempool_package_rbf "mempool_package_rbf.py" COST 5)
add_functional_test(mempool_packages "mempool_packages.py" COST 5)
add_functional_test(mempool_sigoplimit "mempool_sigoplimit.py" COST 5)
add_functional_test(mempool_truc "mempool_truc.py" COST 5)
add_functional_test(mempool_unbroadcast "mempool_unbroadcast.py" COST 5)
add_functional_test(mining_basic "mining_basic.py" COST 5)
add_functional_test(mining_mainnet "mining_mainnet.py" COST 5)
add_functional_test(mining_prioritisetransaction "mining_prioritisetransaction.py" COST 5)
add_functional_test(mining_template_verification "mining_template_verification.py" COST 5)
add_functional_test(p2p_add_connections "p2p_add_connections.py" COST 5)
add_functional_test(p2p_addr_relay "p2p_addr_relay.py" COST 5)
add_functional_test(p2p_addr_selfannouncement "p2p_addr_selfannouncement.py" COST 5)
add_functional_test(p2p_addrfetch "p2p_addrfetch.py" COST 5)
add_functional_test(p2p_addrv2_relay "p2p_addrv2_relay.py" COST 5)
add_functional_test(p2p_blocksonly "p2p_blocksonly.py" COST 5)
add_functional_test(p2p_compactblocks_hb_v1 "p2p_compactblocks_hb.py --v1transport" COST 5)
add_functional_test(p2p_compactblocks_hb_v2 "p2p_compactblocks_hb.py --v2transport" COST 5)
add_functional_test(p2p_disconnect_ban_v1 "p2p_disconnect_ban.py --v1transport" COST 5)
add_functional_test(p2p_disconnect_ban_v2 "p2p_disconnect_ban.py --v2transport" COST 5)
add_functional_test(p2p_eviction "p2p_eviction.py" COST 5)
add_functional_test(p2p_filter "p2p_filter.py" COST 5)
add_functional_test(p2p_fingerprint "p2p_fingerprint.py" COST 5)
add_functional_test(p2p_getaddr_caching "p2p_getaddr_caching.py" COST 5)
add_functional_test(p2p_getdata "p2p_getdata.py" COST 5)
add_functional_test(p2p_ibd_stalling_v1 "p2p_ibd_stalling.py --v1transport" COST 5)
add_functional_test(p2p_ibd_stalling_v2 "p2p_ibd_stalling.py --v2transport" COST 5)
add_functional_test(p2p_initial_headers_sync "p2p_initial_headers_sync.py" COST 5)
add_functional_test(p2p_invalid_block_v1 "p2p_invalid_block.py --v1transport" COST 5)
add_functional_test(p2p_invalid_block_v2 "p2p_invalid_block.py --v2transport" COST 5)
add_functional_test(p2p_invalid_locator "p2p_invalid_locator.py" COST 5)
add_functional_test(p2p_invalid_tx_v1 "p2p_invalid_tx.py --v1transport" COST 5)
add_functional_test(p2p_invalid_tx_v2 "p2p_invalid_tx.py --v2transport" COST 5)
add_functional_test(p2p_leak "p2p_leak.py" COST 5)
add_functional_test(p2p_leak_tx_v1 "p2p_leak_tx.py --v1transport" COST 5)
add_functional_test(p2p_leak_tx_v2 "p2p_leak_tx.py --v2transport" COST 5)
add_functional_test(p2p_message_capture "p2p_message_capture.py" COST 5)
add_functional_test(p2p_mutated_blocks "p2p_mutated_blocks.py" COST 5)
add_functional_test(p2p_net_deadlock_v1 "p2p_net_deadlock.py --v1transport" COST 5)
add_functional_test(p2p_net_deadlock_v2 "p2p_net_deadlock.py --v2transport" COST 5)
add_functional_test(p2p_nobloomfilter_messages "p2p_nobloomfilter_messages.py" COST 5)
add_functional_test(p2p_outbound_eviction "p2p_outbound_eviction.py" COST 5)
add_functional_test(p2p_ping "p2p_ping.py" COST 5)
add_functional_test(p2p_sendtxrcncl "p2p_sendtxrcncl.py" COST 5)
add_functional_test(p2p_tx_privacy "p2p_tx_privacy.py" COST 5)
add_functional_test(p2p_unrequested_blocks "p2p_unrequested_blocks.py" COST 5)
add_functional_test(p2p_v2_encrypted "p2p_v2_encrypted.py" COST 5)
add_functional_test(p2p_v2_misbehaving "p2p_v2_misbehaving.py" COST 5)
add_functional_test(p2p_v2_transport "p2p_v2_transport.py" COST 5)
add_functional_test(rpc_blockchain_v1 "rpc_blockchain.py --v1transport" COST 5)
add_functional_test(rpc_blockchain_v2 "rpc_blockchain.py --v2transport" COST 5)
add_functional_test(rpc_decodescript "rpc_decodescript.py" COST 5)
add_functional_test(rpc_deprecated "rpc_deprecated.py" COST 5)
add_functional_test(rpc_deriveaddresses "rpc_deriveaddresses.py" COST 5)
add_functional_test(rpc_deriveaddresses_usecli "rpc_deriveaddresses.py --usecli" COST 5)
add_functional_test(rpc_dumptxoutset "rpc_dumptxoutset.py" COST 5)
add_functional_test(rpc_estimatefee "rpc_estimatefee.py" COST 5)
add_functional_test(rpc_generate "rpc_generate.py" COST 5)
add_functional_test(rpc_getblockfilter "rpc_getblockfilter.py" COST 5)
add_functional_test(rpc_getblockfrompeer "rpc_getblockfrompeer.py" COST 5)
add_functional_test(rpc_getblockstats "rpc_getblockstats.py" COST 5)
add_functional_test(rpc_getdescriptoractivity "rpc_getdescriptoractivity.py" COST 5)
add_functional_test(rpc_invalidateblock "rpc_invalidateblock.py" COST 5)
add_functional_test(rpc_named_arguments "rpc_named_arguments.py" COST 5)
add_functional_test(rpc_net_v1 "rpc_net.py --v1transport" COST 5)
add_functional_test(rpc_net_v2 "rpc_net.py --v2transport" COST 5)
add_functional_test(rpc_preciousblock "rpc_preciousblock.py" COST 5)
add_functional_test(rpc_rawtransaction "rpc_rawtransaction.py" COST 5)
add_functional_test(rpc_scanblocks "rpc_scanblocks.py" COST 5)
add_functional_test(rpc_scantxoutset "rpc_scantxoutset.py" COST 5)
add_functional_test(rpc_setban_v1 "rpc_setban.py --v1transport" COST 5)
add_functional_test(rpc_setban_v2 "rpc_setban.py --v2transport" COST 5)
add_functional_test(rpc_signmessagewithprivkey "rpc_signmessagewithprivkey.py" COST 5)
add_functional_test(rpc_signrawtransactionwithkey "rpc_signrawtransactionwithkey.py" COST 5)
add_functional_test(rpc_uptime "rpc_uptime.py" COST 5)
add_functional_test(rpc_users "rpc_users.py" COST 5)
add_functional_test(rpc_whitelist "rpc_whitelist.py" COST 5)
if(IS_POSIX)
    add_functional_test(tool_bitcoin "tool_bitcoin.py" COST 5)
endif()
add_functional_test(tool_utxo_to_sqlite "tool_utxo_to_sqlite.py" COST 5)
if(ENABLE_IPC)
    add_functional_test(interface_ipc "interface_ipc.py" COST 5)
endif()
add_functional_test(feature_anchors "feature_anchors.py" COST 5)
add_functional_test(feature_blocksdir "feature_blocksdir.py" COST 5)
add_functional_test(feature_coinstatsindex "feature_coinstatsindex.py" COST 5)
add_functional_test(feature_dirsymlinks "feature_dirsymlinks.py" COST 5)
add_functional_test(feature_framework_startup_failures "feature_framework_startup_failures.py" COST 5)
add_functional_test(feature_framework_testshell "feature_framework_testshell.py" COST 5)
add_functional_test(feature_help "feature_help.py" COST 5)
add_functional_test(feature_presegwit_node_upgrade "feature_presegwit_node_upgrade.py" COST 5)
add_functional_test(feature_remove_pruned_files_on_startup "feature_remove_pruned_files_on_startup.py" COST 5)
add_functional_test(feature_settings "feature_settings.py" COST 5)
add_functional_test(feature_shutdown "feature_shutdown.py" COST 5)
add_functional_test(mempool_datacarrier "mempool_datacarrier.py" COST 5)
add_functional_test(p2p_handshake "p2p_handshake.py" COST 5)
add_functional_test(p2p_handshake_v2 "p2p_handshake.py --v2transport" COST 5)
add_functional_test(p2p_i2p_ports "p2p_i2p_ports.py" COST 5)
add_functional_test(p2p_i2p_sessions "p2p_i2p_sessions.py" COST 5)
add_functional_test(p2p_ibd_txrelay "p2p_ibd_txrelay.py" COST 5)
add_functional_test(p2p_permissions "p2p_permissions.py" COST 5)
add_functional_test(p2p_seednode "p2p_seednode.py" COST 5)
add_functional_test(rpc_getdescriptorinfo "rpc_getdescriptorinfo.py" COST 5)
add_functional_test(rpc_help "rpc_help.py" COST 5)
add_functional_test(rpc_mempool_info "rpc_mempool_info.py" COST 5)
add_functional_test(tool_rpcauth "tool_rpcauth.py" COST 5)

# POSIX-only tests (Linux, macOS, etc. - not Windows)
if(IS_POSIX)
    add_functional_test(feature_posix_fs_permissions "feature_posix_fs_permissions.py" COST 5 LABELS "posix_only")
endif()

# Linux-only tests
if(IS_LINUX)
    add_functional_test(feature_bind_extra "feature_bind_extra.py" COST 17 LABELS "linux_only")
    add_functional_test(rpc_bind_ipv4 "rpc_bind.py --ipv4" COST 5 LABELS "linux_only")
    add_functional_test(rpc_bind_ipv6 "rpc_bind.py --ipv6" COST 5 LABELS "linux_only")
    add_functional_test(rpc_bind_nonloopback "rpc_bind.py --nonloopback" COST 5 LABELS "linux_only")
endif()

# USDT tests (require Linux and BPF permissions)
if(ENABLE_USDT_TESTS AND IS_LINUX)
    add_functional_test(interface_usdt_coinselection "interface_usdt_coinselection.py" COST 60 LABELS "usdt;linux_only")
    add_functional_test(interface_usdt_mempool "interface_usdt_mempool.py" COST 55 LABELS "usdt;linux_only")
    add_functional_test(interface_usdt_net "interface_usdt_net.py" COST 50 LABELS "usdt;linux_only")
    add_functional_test(interface_usdt_utxocache "interface_usdt_utxocache.py" COST 45 LABELS "usdt;linux_only")
    add_functional_test(interface_usdt_validation "interface_usdt_validation.py" COST 40 LABELS "usdt;linux_only")
endif()

# Previous releases tests
if(ENABLE_PREVIOUS_RELEASES_TESTS)
    add_functional_test(mempool_compatibility "mempool_compatibility.py" COST 50 LABELS "previous_releases")
    add_functional_test(feature_unsupported_utxo_db "feature_unsupported_utxo_db.py" COST 45 LABELS "previous_releases")
    add_functional_test(feature_coinstatsindex_compatibility "feature_coinstatsindex_compatibility.py" COST 40 LABELS "previous_releases")
    if(ENABLE_WALLET)
        add_functional_test(wallet_backwards_compatibility "wallet_backwards_compatibility.py" COST 35 LABELS "previous_releases;wallet")
        add_functional_test(wallet_migration "wallet_migration.py" COST 5 LABELS "previous_releases;wallet")
    endif()
endif()

# Special network tests (require specific routable addresses to be assigned to network interfaces)
if(ENABLE_SPECIAL_NETWORK_TESTS)
    add_functional_test(feature_bind_port_externalip "feature_bind_port_externalip.py" COST 40 LABELS "special_network")
    add_functional_test(feature_bind_port_discover "feature_bind_port_discover.py" COST 40 LABELS "special_network")
endif()

# Coverage reporting test - runs after all functional tests complete
if(ENABLE_RPC_COVERAGE)
    add_test(
        NAME bitcoin.functional.coverage-report
        COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/functional/report_coverage.py ${CMAKE_CURRENT_BINARY_DIR}/coverage
        WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    )

    set_tests_properties(bitcoin.functional.coverage-report PROPERTIES
        LABELS "rpc_coverage"
        # This test runs after all functional tests complete
        FIXTURES_CLEANUP "functional_cache"
    )
endif()
