# ubuntu:noble-20241015
FROM ubuntu:noble-20241015@sha256:278628f08d4979fb9af9ead44277dbc9c92c2465922310916ad0c46ec9999295

ENV DEBIAN_FRONTEND=noninteractive

# CI Base Packages
RUN apt-get update && apt-get install --yes \
  bison \
  build-essential \
  ca-certificates \
  ccache \
  cmake \
  curl \
  e2fsprogs \
  git \
  ninja-build  \
  pkg-config \
  procps \
  python3 \
  python3-pip \
  rsync \
  wget \
  && rm -rf /var/lib/apt/lists/*

CMD ["bash"]
