FROM ubuntu:24.04
ENV VERSION_CODENAME="noble"
ENV DEBIAN_FRONTEND=noninteractive

# CI Base Packages
RUN apt-get update
RUN apt-get install --yes \
  bison \
  build-essential \
  ca-certificates \
  ccache \
  cmake \
  curl \
  e2fsprogs \
  git \
  ninja-build  \
  pkg-config \
  procps \
  python3 \
  python3-pip \
  rsync \
  wget \
  && rm -rf /var/lib/apt/lists/*

CMD ["bash"]
