line-length = 120
indent-width = 4

[format]
exclude = [
    # Imported code.
    "src/crc32c/**/*.py",
    "src/crypto/ctaes/**/*.py",
    "src/ipc/libmultiprocess/**/*.py",
    "src/leveldb/**/*.py",
    "src/minisketch/**/*.py",
    "src/secp256k1/**/*.py",
    # Existing functional tests. Remove entries as files are formatted.
    "test/functional/combine_logs.py",
    "test/functional/create_cache.py",
    "test/functional/data/__init__.py",
    "test/functional/data/invalid_txs.py",
    "test/functional/example_test.py",
    "test/functional/feature_abortnode.py",
    "test/functional/feature_addrman.py",
    "test/functional/feature_anchors.py",
    "test/functional/feature_asmap.py",
    "test/functional/feature_assumeutxo.py",
    "test/functional/feature_assumevalid.py",
    "test/functional/feature_bind_extra.py",
    "test/functional/feature_bind_port_discover.py",
    "test/functional/feature_bind_port_externalip.py",
    "test/functional/feature_bip68_sequence.py",
    "test/functional/feature_block.py",
    "test/functional/feature_blocksdir.py",
    "test/functional/feature_blocksxor.py",
    "test/functional/feature_chain_tiebreaks.py",
    "test/functional/feature_cltv.py",
    "test/functional/feature_coinstatsindex.py",
    "test/functional/feature_coinstatsindex_compatibility.py",
    "test/functional/feature_config_args.py",
    "test/functional/feature_csv_activation.py",
    "test/functional/feature_dbcrash.py",
    "test/functional/feature_dersig.py",
    "test/functional/feature_dirsymlinks.py",
    "test/functional/feature_discover.py",
    "test/functional/feature_fastprune.py",
    "test/functional/feature_fee_estimation.py",
    "test/functional/feature_filelock.py",
    "test/functional/feature_framework_miniwallet.py",
    "test/functional/feature_framework_startup_failures.py",
    "test/functional/feature_framework_testshell.py",
    "test/functional/feature_framework_unit_tests.py",
    "test/functional/feature_help.py",
    "test/functional/feature_includeconf.py",
    "test/functional/feature_index_prune.py",
    "test/functional/feature_init.py",
    "test/functional/feature_loadblock.py",
    "test/functional/feature_logging.py",
    "test/functional/feature_maxtipage.py",
    "test/functional/feature_maxuploadtarget.py",
    "test/functional/feature_minchainwork.py",
    "test/functional/feature_notifications.py",
    "test/functional/feature_nulldummy.py",
    "test/functional/feature_port.py",
    "test/functional/feature_posix_fs_permissions.py",
    "test/functional/feature_presegwit_node_upgrade.py",
    "test/functional/feature_proxy.py",
    "test/functional/feature_prune_stale_fork.py",
    "test/functional/feature_pruning.py",
    "test/functional/feature_rbf.py",
    "test/functional/feature_reindex.py",
    "test/functional/feature_reindex_init.py",
    "test/functional/feature_reindex_readonly.py",
    "test/functional/feature_remove_pruned_files_on_startup.py",
    "test/functional/feature_segwit.py",
    "test/functional/feature_settings.py",
    "test/functional/feature_shutdown.py",
    "test/functional/feature_signet.py",
    "test/functional/feature_startupnotify.py",
    "test/functional/feature_taproot.py",
    "test/functional/feature_torcontrol.py",
    "test/functional/feature_uacomment.py",
    "test/functional/feature_unsupported_utxo_db.py",
    "test/functional/feature_utxo_set_hash.py",
    "test/functional/feature_versionbits_warning.py",
    "test/functional/interface_bitcoin_cli.py",
    "test/functional/interface_http.py",
    "test/functional/interface_ipc.py",
    "test/functional/interface_ipc_cli.py",
    "test/functional/interface_ipc_mining.py",
    "test/functional/interface_rest.py",
    "test/functional/interface_rpc.py",
    "test/functional/interface_usdt_coinselection.py",
    "test/functional/interface_usdt_mempool.py",
    "test/functional/interface_usdt_net.py",
    "test/functional/interface_usdt_utxocache.py",
    "test/functional/interface_usdt_validation.py",
    "test/functional/interface_zmq.py",
    "test/functional/mempool_accept.py",
    "test/functional/mempool_accept_wtxid.py",
    "test/functional/mempool_cluster.py",
    "test/functional/mempool_compatibility.py",
    "test/functional/mempool_datacarrier.py",
    "test/functional/mempool_dust.py",
    "test/functional/mempool_ephemeral_dust.py",
    "test/functional/mempool_expiry.py",
    "test/functional/mempool_limit.py",
    "test/functional/mempool_package_limits.py",
    "test/functional/mempool_package_rbf.py",
    "test/functional/mempool_packages.py",
    "test/functional/mempool_persist.py",
    "test/functional/mempool_reorg.py",
    "test/functional/mempool_resurrect.py",
    "test/functional/mempool_sigoplimit.py",
    "test/functional/mempool_spend_coinbase.py",
    "test/functional/mempool_truc.py",
    "test/functional/mempool_unbroadcast.py",
    "test/functional/mempool_updatefromblock.py",
    "test/functional/mining_basic.py",
    "test/functional/mining_getblocktemplate_longpoll.py",
    "test/functional/mining_mainnet.py",
    "test/functional/mining_prioritisetransaction.py",
    "test/functional/mining_template_verification.py",
    "test/functional/mocks/invalid_signer.py",
    "test/functional/mocks/multi_signers.py",
    "test/functional/mocks/no_signer.py",
    "test/functional/mocks/signer.py",
    "test/functional/p2p_1p1c_network.py",
    "test/functional/p2p_add_connections.py",
    "test/functional/p2p_addr_relay.py",
    "test/functional/p2p_addr_selfannouncement.py",
    "test/functional/p2p_addrfetch.py",
    "test/functional/p2p_addrv2_relay.py",
    "test/functional/p2p_bip434_feature.py",
    "test/functional/p2p_block_sync.py",
    "test/functional/p2p_blockfilters.py",
    "test/functional/p2p_blocksonly.py",
    "test/functional/p2p_compactblocks.py",
    "test/functional/p2p_compactblocks_blocksonly.py",
    "test/functional/p2p_compactblocks_hb.py",
    "test/functional/p2p_disconnect_ban.py",
    "test/functional/p2p_dns_seeds.py",
    "test/functional/p2p_eviction.py",
    "test/functional/p2p_feefilter.py",
    "test/functional/p2p_filter.py",
    "test/functional/p2p_fingerprint.py",
    "test/functional/p2p_getaddr_caching.py",
    "test/functional/p2p_getdata.py",
    "test/functional/p2p_handshake.py",
    "test/functional/p2p_headers_sync_with_minchainwork.py",
    "test/functional/p2p_i2p_ports.py",
    "test/functional/p2p_i2p_sessions.py",
    "test/functional/p2p_ibd_stalling.py",
    "test/functional/p2p_ibd_txrelay.py",
    "test/functional/p2p_initial_headers_sync.py",
    "test/functional/p2p_invalid_block.py",
    "test/functional/p2p_invalid_locator.py",
    "test/functional/p2p_invalid_messages.py",
    "test/functional/p2p_invalid_tx.py",
    "test/functional/p2p_leak.py",
    "test/functional/p2p_leak_tx.py",
    "test/functional/p2p_message_capture.py",
    "test/functional/p2p_mutated_blocks.py",
    "test/functional/p2p_net_deadlock.py",
    "test/functional/p2p_nobloomfilter_messages.py",
    "test/functional/p2p_node_network_limited.py",
    "test/functional/p2p_opportunistic_1p1c.py",
    "test/functional/p2p_orphan_handling.py",
    "test/functional/p2p_outbound_eviction.py",
    "test/functional/p2p_permissions.py",
    "test/functional/p2p_ping.py",
    "test/functional/p2p_private_broadcast.py",
    "test/functional/p2p_private_broadcast_cap.py",
    "test/functional/p2p_private_broadcast_retry_v1.py",
    "test/functional/p2p_seednode.py",
    "test/functional/p2p_segwit.py",
    "test/functional/p2p_sendheaders.py",
    "test/functional/p2p_sendtxrcncl.py",
    "test/functional/p2p_timeouts.py",
    "test/functional/p2p_tx_download.py",
    "test/functional/p2p_tx_privacy.py",
    "test/functional/p2p_unrequested_blocks.py",
    "test/functional/p2p_v2_encrypted.py",
    "test/functional/p2p_v2_misbehaving.py",
    "test/functional/p2p_v2_transport.py",
    "test/functional/rpc_bind.py",
    "test/functional/rpc_blockchain.py",
    "test/functional/rpc_createmultisig.py",
    "test/functional/rpc_decodescript.py",
    "test/functional/rpc_deprecated.py",
    "test/functional/rpc_deriveaddresses.py",
    "test/functional/rpc_dumptxoutset.py",
    "test/functional/rpc_estimatefee.py",
    "test/functional/rpc_generate.py",
    "test/functional/rpc_getblockfilter.py",
    "test/functional/rpc_getblockfrompeer.py",
    "test/functional/rpc_getblockstats.py",
    "test/functional/rpc_getchaintips.py",
    "test/functional/rpc_getdescriptoractivity.py",
    "test/functional/rpc_getdescriptorinfo.py",
    "test/functional/rpc_gettxspendingprevout.py",
    "test/functional/rpc_help.py",
    "test/functional/rpc_invalid_address_message.py",
    "test/functional/rpc_invalidateblock.py",
    "test/functional/rpc_misc.py",
    "test/functional/rpc_named_arguments.py",
    "test/functional/rpc_net.py",
    "test/functional/rpc_orphans.py",
    "test/functional/rpc_packages.py",
    "test/functional/rpc_preciousblock.py",
    "test/functional/rpc_psbt.py",
    "test/functional/rpc_rawtransaction.py",
    "test/functional/rpc_scanblocks.py",
    "test/functional/rpc_scantxoutset.py",
    "test/functional/rpc_setban.py",
    "test/functional/rpc_signer.py",
    "test/functional/rpc_signmessagewithprivkey.py",
    "test/functional/rpc_signrawtransactionwithkey.py",
    "test/functional/rpc_txoutproof.py",
    "test/functional/rpc_uptime.py",
    "test/functional/rpc_users.py",
    "test/functional/rpc_validateaddress.py",
    "test/functional/rpc_whitelist.py",
    "test/functional/test_framework/__init__.py",
    "test/functional/test_framework/address.py",
    "test/functional/test_framework/authproxy.py",
    "test/functional/test_framework/blockfilter.py",
    "test/functional/test_framework/blocktools.py",
    "test/functional/test_framework/compressor.py",
    "test/functional/test_framework/coverage.py",
    "test/functional/test_framework/crypto/bip324_cipher.py",
    "test/functional/test_framework/crypto/chacha20.py",
    "test/functional/test_framework/crypto/ellswift.py",
    "test/functional/test_framework/crypto/hkdf.py",
    "test/functional/test_framework/crypto/muhash.py",
    "test/functional/test_framework/crypto/poly1305.py",
    "test/functional/test_framework/crypto/ripemd160.py",
    "test/functional/test_framework/crypto/secp256k1.py",
    "test/functional/test_framework/crypto/siphash.py",
    "test/functional/test_framework/descriptors.py",
    "test/functional/test_framework/extendedkey.py",
    "test/functional/test_framework/ipc_util.py",
    "test/functional/test_framework/key.py",
    "test/functional/test_framework/mempool_util.py",
    "test/functional/test_framework/messages.py",
    "test/functional/test_framework/netutil.py",
    "test/functional/test_framework/p2p.py",
    "test/functional/test_framework/psbt.py",
    "test/functional/test_framework/script.py",
    "test/functional/test_framework/script_util.py",
    "test/functional/test_framework/segwit_addr.py",
    "test/functional/test_framework/socks5.py",
    "test/functional/test_framework/test_framework.py",
    "test/functional/test_framework/test_node.py",
    "test/functional/test_framework/test_shell.py",
    "test/functional/test_framework/util.py",
    "test/functional/test_framework/v2_p2p.py",
    "test/functional/test_framework/wallet.py",
    "test/functional/test_framework/wallet_util.py",
    "test/functional/test_runner.py",
    "test/functional/tool_bench_sanity_check.py",
    "test/functional/tool_bitcoin.py",
    "test/functional/tool_bitcoin_chainstate.py",
    "test/functional/tool_rpcauth.py",
    "test/functional/tool_signet_miner.py",
    "test/functional/tool_utils.py",
    "test/functional/tool_utxo_to_sqlite.py",
    "test/functional/tool_wallet.py",
    "test/functional/wallet_abandonconflict.py",
    "test/functional/wallet_address_types.py",
    "test/functional/wallet_anchor.py",
    "test/functional/wallet_assumeutxo.py",
    "test/functional/wallet_avoid_mixing_output_types.py",
    "test/functional/wallet_avoidreuse.py",
    "test/functional/wallet_backup.py",
    "test/functional/wallet_backwards_compatibility.py",
    "test/functional/wallet_balance.py",
    "test/functional/wallet_basic.py",
    "test/functional/wallet_blank.py",
    "test/functional/wallet_bumpfee.py",
    "test/functional/wallet_change_address.py",
    "test/functional/wallet_coinbase_category.py",
    "test/functional/wallet_conflicts.py",
    "test/functional/wallet_create_tx.py",
    "test/functional/wallet_createwallet.py",
    "test/functional/wallet_createwalletdescriptor.py",
    "test/functional/wallet_crosschain.py",
    "test/functional/wallet_deprecated_rbf.py",
    "test/functional/wallet_descriptor.py",
    "test/functional/wallet_disable.py",
    "test/functional/wallet_encryption.py",
    "test/functional/wallet_exported_watchonly.py",
    "test/functional/wallet_fallbackfee.py",
    "test/functional/wallet_fast_rescan.py",
    "test/functional/wallet_fundrawtransaction.py",
    "test/functional/wallet_gethdkeys.py",
    "test/functional/wallet_groups.py",
    "test/functional/wallet_hd.py",
    "test/functional/wallet_importdescriptors.py",
    "test/functional/wallet_importprunedfunds.py",
    "test/functional/wallet_keypool.py",
    "test/functional/wallet_keypool_topup.py",
    "test/functional/wallet_labels.py",
    "test/functional/wallet_listdescriptors.py",
    "test/functional/wallet_listreceivedby.py",
    "test/functional/wallet_listsinceblock.py",
    "test/functional/wallet_listtransactions.py",
    "test/functional/wallet_migration.py",
    "test/functional/wallet_miniscript.py",
    "test/functional/wallet_miniscript_decaying_multisig_descriptor_psbt.py",
    "test/functional/wallet_multisig_descriptor_psbt.py",
    "test/functional/wallet_multiwallet.py",
    "test/functional/wallet_musig.py",
    "test/functional/wallet_orphanedreward.py",
    "test/functional/wallet_reindex.py",
    "test/functional/wallet_reorgsrestore.py",
    "test/functional/wallet_rescan_unconfirmed.py",
    "test/functional/wallet_resendwallettransactions.py",
    "test/functional/wallet_send.py",
    "test/functional/wallet_sendall.py",
    "test/functional/wallet_sendmany.py",
    "test/functional/wallet_signer.py",
    "test/functional/wallet_signmessagewithaddress.py",
    "test/functional/wallet_signrawtransactionwithwallet.py",
    "test/functional/wallet_simulaterawtx.py",
    "test/functional/wallet_spend_unconfirmed.py",
    "test/functional/wallet_startup.py",
    "test/functional/wallet_taproot.py",
    "test/functional/wallet_timelock.py",
    "test/functional/wallet_transactiontime_rescan.py",
    "test/functional/wallet_txn_clone.py",
    "test/functional/wallet_txn_doublespend.py",
    "test/functional/wallet_v3_txs.py",
]


[lint]
select = [
    "B006", # mutable-argument-default
    "B008", # function-call-in-default-argument
    "E", # pycodestyle errors
    "F", # pyflakes errors
    "PLE",  # Pylint errors
    "RUF001", # ambiguous-unicode-character-string
    "RUF002", # ambiguous-unicode-character-docstring
    "RUF003", # ambiguous-unicode-character-comment
    "W", # pycodestyle warnings
]
ignore = [
    "E501", # line too long
    "E741", # ambiguous-variable-name
]
