[src]
include = ["test/functional/*.py", "contrib/devtools/*.py"]

[environment]
root = ["test/functional"]

[rules]
invalid-argument-type = "ignore"
invalid-method-override = "ignore"
not-subscriptable = "ignore"
unresolved-attribute = "ignore"
unsupported-operator = "ignore"
