[src]
include = ["test/functional/**", "contrib/devtools/**"]

[environment]
root = ["test/functional"]

[rules]
missing-argument = "ignore"
no-matching-overload = "ignore"
invalid-return-type = "ignore"
possibly-missing-attribute = "ignore"
too-many-positional-arguments = "ignore"
unused-ignore-comment = "ignore"
unused-type-ignore-comment = "ignore"
