name: 'Checkout current merge commit'
description: 'Always check out a current merge commit, even on re-runs'
outputs:
  commit:
    description: 'Commit hash checked out'
    value: ${{ steps.hash.outputs.commit }}
runs:
  using: 'composite'
  steps:
    - name: Checkout base
      uses: actions/checkout@v5

    - name: Merge to master
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          git fetch origin ${{ github.ref }}
          git merge --no-edit ${{ github.sha }}
        fi

    - id: hash
      shell: bash
      run: |
        echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
