name: merge check

on:
  workflow_dispatch: # Must be run manually
    inputs:
      pr_number:
        description: 'Pull request number to test'
        required: true
        type: string

jobs:
  check:
    name: Check mergeability
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR merge commit
        uses: actions/checkout@v5
        with:
          ref: refs/pull/${{ inputs.pr_number }}/merge
          fetch-depth: 1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
          extra-conf: |
            lazy-trees = true

      - name: Set Up Cachix
        uses: cachix/cachix-action@v15
        with:
          name: bitcoin-core
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run `nix flake check`
        run: nix flake check ci/

      - name: Build bitcoind
        run: |
          nix build ci/
